version: '3.1'

services:
  test.api:
    container_name: WebApiii-container
    restart: always
    build:
      dockerfile: WebApiii/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    networks:
      - nginx-network
        
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
